---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: pcfnorm/rootfs
    tag: 1.0.15

inputs:
- name: pcf-pipelines 
- name: pivnet-opsmgr

params:
  GCP_PROJECT_ID:
  GCP_REGION:
  GCP_SERVICE_ACCOUNT_KEY:

run:
  path: pcf-pipelines/install-pcf/gcp/tasks/upload-opsman/task.sh
